// Renders contracts/script/Redbelly.sol from the @gatedpath/chains module. Shared by
// the scaffolder and by the generated project's `chains:sync` script (vendored copy).
/** Solidity constants generated from the chains package so nothing is retyped by hand. */
export function renderRedbellySol(chains) {
  const { addresses, redbellyMainnet, redbellyTestnet } = chains;
  const line = (name, a) => `    address internal constant ${name} = ${a};`;
  const m = addresses.mainnet;
  const t = addresses.testnet;
  return `// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

// Redbelly Network constants, generated by create-redbelly-dapp from the
// gatedpath/chains package (every address verified on ${m.permission.verifiedOn}).
// Don't edit by hand; run \`npm run chains:sync\` when that package updates.
library Redbelly {
    uint256 internal constant MAINNET_CHAIN_ID = ${redbellyMainnet.id};
    uint256 internal constant TESTNET_CHAIN_ID = ${redbellyTestnet.id};

    /// @dev Same address on both networks; getContractAddress("permission") resolves the gate.
${line('BOOTSTRAP_REGISTRY', m.bootstrapRegistry.address)}

${line('MAINNET_PERMISSION', m.permission.address)}
${line('TESTNET_PERMISSION', t.permission.address)}
${line('MAINNET_PRICEFEED', m.pricefeed.address)}
${line('TESTNET_PRICEFEED', t.pricefeed.address)}
${line('MAINNET_ACCREDITED_ISSUER_REGISTRY', m.accreditedIssuerRegistry.address)}
${line('TESTNET_ACCREDITED_ISSUER_REGISTRY', t.accreditedIssuerRegistry.address)}

    /// @dev Safe 1.4.1 canonical deployments, present on 151 and 153.
${line('SAFE_SINGLETON', m.safeSingleton.address)}
${line('SAFE_L2_SINGLETON', m.safeL2Singleton.address)}
${line('SAFE_PROXY_FACTORY', m.safeProxyFactory.address)}
${line('SAFE_FALLBACK_HANDLER', m.safeFallbackHandler.address)}
${line('MULTICALL3', m.multicall3.address)}

    string internal constant MAINNET_RPC = "${redbellyMainnet.rpcUrls.default.http[0]}";
    string internal constant TESTNET_RPC = "${redbellyTestnet.rpcUrls.default.http[0]}";
    string internal constant MAINNET_EXPLORER = "${redbellyMainnet.blockExplorers.default.url}";
    string internal constant TESTNET_EXPLORER = "${redbellyTestnet.blockExplorers.default.url}";

    function isRedbelly(uint256 chainId) internal pure returns (bool) {
        return chainId == MAINNET_CHAIN_ID || chainId == TESTNET_CHAIN_ID;
    }

    function permission(uint256 chainId) internal pure returns (address) {
        if (chainId == MAINNET_CHAIN_ID) return MAINNET_PERMISSION;
        if (chainId == TESTNET_CHAIN_ID) return TESTNET_PERMISSION;
        return address(0);
    }

    function isSafeSingleton(address singleton) internal pure returns (bool) {
        return singleton == SAFE_SINGLETON || singleton == SAFE_L2_SINGLETON;
    }
}
`;
}

