// GENERATED by scripts/sync-chain-facts.mjs from @gatedpath/chains
// (packages/chain-definitions). That package is canonical: every address and URL here
// traces to its src/addresses.ts and src/chains.ts, and through them to RESEARCH.md.
// Do not edit by hand. Run `npm run sync` and commit the result.

export const chainFacts = {
  "verifiedOn": "2026-09-12",
  "nativeCurrency": {
    "name": "Redbelly Network Coin",
    "symbol": "RBNT",
    "decimals": 18
  },
  "mainnet": {
    "id": 151,
    "name": "Redbelly Network Mainnet",
    "rpc": "https://governors.mainnet.redbelly.network",
    "publicRpcs": [
      "https://governors.mainnet.redbelly.network",
      "https://rpc.ankr.com/redbelly_mainnet"
    ],
    "explorer": {
      "name": "Routescan",
      "url": "https://redbelly.routescan.io",
      "apiUrl": "https://api.routescan.io/v2/network/mainnet/evm/151/etherscan/api"
    },
    "addresses": {
      "accreditedIssuerRegistry": {
        "address": "0x2d68f1C50a057a310EeF28DF3199F95A65cE4ac5",
        "verifiedOn": "2026-09-12"
      },
      "bootstrapRegistry": {
        "address": "0xDAFEA492D9c6733ae3d56b7Ed1ADB60692c98Bc5",
        "verifiedOn": "2026-09-12"
      },
      "eip2935History": {
        "address": "0x0000F90827F1C53a10cb7A02335B175320002935",
        "verifiedOn": "2026-09-12"
      },
      "gasfees": {
        "address": "0x292Cc6D79E95B2848579735c24B70215179D4a33",
        "verifiedOn": "2026-09-12"
      },
      "multicall3": {
        "address": "0xcA11bde05977b3631167028862bE2a173976CA11",
        "verifiedOn": "2026-09-12"
      },
      "nicksDeployer": {
        "address": "0x4e59b44847b379578588920cA78FbF26c0B4956C",
        "verifiedOn": "2026-09-12"
      },
      "permission": {
        "address": "0xcb385cD90ca6b219798F57B4a7958897e91A9163",
        "verifiedOn": "2026-09-12"
      },
      "pricefeed": {
        "address": "0x0CD42d829F88fe539f710E9b7692C70b94aaEad4",
        "verifiedOn": "2026-09-12"
      },
      "safeCreateCall": {
        "address": "0x9b35Af71d77eaf8d7e40252370304687390A1A52",
        "verifiedOn": "2026-09-12"
      },
      "safeFallbackHandler": {
        "address": "0xfd0732Dc9E303f09fCEf3a7388Ad10A83459Ec99",
        "verifiedOn": "2026-09-12"
      },
      "safeL2Singleton": {
        "address": "0x29fcB43b46531BcA003ddC8FCB67FFE91900C762",
        "verifiedOn": "2026-09-12"
      },
      "safeMultiSend": {
        "address": "0x38869bf66a61cF6bDB996A6aE40D5853Fd43B526",
        "verifiedOn": "2026-09-12"
      },
      "safeMultiSendCallOnly": {
        "address": "0x9641d764fc13c8B624c04430C7356C1C7C8102e2",
        "verifiedOn": "2026-09-12"
      },
      "safeProxyFactory": {
        "address": "0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67",
        "verifiedOn": "2026-09-12"
      },
      "safeSignMessageLib": {
        "address": "0xd53cd0aB83D845Ac265BE939c57F53AD838012c9",
        "verifiedOn": "2026-09-12"
      },
      "safeSimulateTxAccessor": {
        "address": "0x3d4BA2E0884aa488718476ca2FB8Efc291A46199",
        "verifiedOn": "2026-09-12"
      },
      "safeSingleton": {
        "address": "0x41675C099F32341bf84BFc5382aF534df5C7461a",
        "verifiedOn": "2026-09-12"
      },
      "safeSingletonFactory": {
        "address": "0x914d7Fec6aaC8cd542e72Bca78B30650d45643d7",
        "verifiedOn": "2026-09-12"
      }
    }
  },
  "testnet": {
    "id": 153,
    "name": "Redbelly Network Testnet",
    "rpc": "https://governors.testnet.redbelly.network",
    "publicRpcs": [
      "https://governors.testnet.redbelly.network"
    ],
    "explorer": {
      "name": "Routescan",
      "url": "https://redbelly.testnet.routescan.io",
      "apiUrl": "https://api.routescan.io/v2/network/testnet/evm/153/etherscan/api"
    },
    "addresses": {
      "accreditedIssuerRegistry": {
        "address": "0x6aEe06F4052ff6d01Ed7E13Fa5Ab53675756A057",
        "verifiedOn": "2026-09-12"
      },
      "bootstrapRegistry": {
        "address": "0xDAFEA492D9c6733ae3d56b7Ed1ADB60692c98Bc5",
        "verifiedOn": "2026-09-12"
      },
      "eip2935History": {
        "address": "0x0000F90827F1C53a10cb7A02335B175320002935",
        "verifiedOn": "2026-09-12"
      },
      "gasfees": {
        "address": "0x292Cc6D79E95B2848579735c24B70215179D4a33",
        "verifiedOn": "2026-09-12"
      },
      "multicall3": {
        "address": "0xcA11bde05977b3631167028862bE2a173976CA11",
        "verifiedOn": "2026-09-12"
      },
      "nicksDeployer": {
        "address": "0x4e59b44847b379578588920cA78FbF26c0B4956C",
        "verifiedOn": "2026-09-12"
      },
      "permission": {
        "address": "0x519ba1b48D571FD92FAF6FE4D20fe74Ca435B690",
        "verifiedOn": "2026-09-12"
      },
      "permit2": {
        "address": "0x000000000022D473030F116dDEE9F6B43aC78BA3",
        "verifiedOn": "2026-09-12"
      },
      "pricefeed": {
        "address": "0xBf207257412D3672F9C772ef263583611B98039a",
        "verifiedOn": "2026-09-12"
      },
      "safeCreateCall": {
        "address": "0x9b35Af71d77eaf8d7e40252370304687390A1A52",
        "verifiedOn": "2026-09-12"
      },
      "safeFallbackHandler": {
        "address": "0xfd0732Dc9E303f09fCEf3a7388Ad10A83459Ec99",
        "verifiedOn": "2026-09-12"
      },
      "safeL2Singleton": {
        "address": "0x29fcB43b46531BcA003ddC8FCB67FFE91900C762",
        "verifiedOn": "2026-09-12"
      },
      "safeMultiSend": {
        "address": "0x38869bf66a61cF6bDB996A6aE40D5853Fd43B526",
        "verifiedOn": "2026-09-12"
      },
      "safeMultiSendCallOnly": {
        "address": "0x9641d764fc13c8B624c04430C7356C1C7C8102e2",
        "verifiedOn": "2026-09-12"
      },
      "safeProxyFactory": {
        "address": "0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67",
        "verifiedOn": "2026-09-12"
      },
      "safeSignMessageLib": {
        "address": "0xd53cd0aB83D845Ac265BE939c57F53AD838012c9",
        "verifiedOn": "2026-09-12"
      },
      "safeSimulateTxAccessor": {
        "address": "0x3d4BA2E0884aa488718476ca2FB8Efc291A46199",
        "verifiedOn": "2026-09-12"
      },
      "safeSingleton": {
        "address": "0x41675C099F32341bf84BFc5382aF534df5C7461a",
        "verifiedOn": "2026-09-12"
      },
      "safeSingletonFactory": {
        "address": "0x914d7Fec6aaC8cd542e72Bca78B30650d45643d7",
        "verifiedOn": "2026-09-12"
      }
    }
  },
  "keyedRpcs": {
    "mainnet": {
      "uniblock": {
        "url": "https://api.uniblock.dev/uni/v1/json-rpc?chainId=151",
        "header": "x-api-key"
      }
    }
  },
  "agentNotes": "Redbelly Network, facts for a coding agent (verified 2026-09-12).\nChain IDs: 151 mainnet, 153 testnet. Native coin RBNT, 18 decimals.\nRPCs: https://governors.mainnet.redbelly.network and https://governors.testnet.redbelly.network. Ankr also serves mainnet at https://rpc.ankr.com/redbelly_mainnet.\nExplorers: https://redbelly.routescan.io (151) and https://redbelly.testnet.routescan.io (153), Etherscan-style API under https://api.routescan.io/v2/network/{mainnet,testnet}/evm/{151,153}/etherscan/api.\nGas model in one sentence: gas is priced in US dollars (a 21,000-gas transfer costs US$0.01) and converted to RBNT at execution from an on-chain price feed, so RBNT fees move with the RBNT price and the priority fee is always zero.\nEvery wallet must pass isAllowed before it can transact: permission.isAllowed(address) on the contract the bootstrap registry (0xDAFEA492D9c6733ae3d56b7Ed1ADB60692c98Bc5, both chains) names as \"permission\" must return true, which requires identity verification at https://access.redbelly.network. Check it before deploying or sending.\nCompile for prague with solc 0.8.30. Transient storage, PUSH0, MCOPY and the Prague precompiles are all present.\nBlocks are produced on demand; poll aggressively. There is no block cadence: with no traffic there is no block, and a transaction lands within seconds or not at all. Do not sleep for a block time.\nNo debug or trace RPC methods. debug_* and trace_* are not served by the governors endpoints; net_version is not served either."
} as const;

export type ChainFacts = typeof chainFacts;
