// Pure renderers: source in, text out. No I/O, no clock, no randomness, so the same
// source always renders the same bytes. Conventions checked on 2026-09-12:
//   Claude Code  ./CLAUDE.md, plain markdown, HTML comments stripped before use
//                (code.claude.com/docs/en/memory)
//   Codex CLI    AGENTS.md walked from the git root, 32 KiB combined budget
//                (learn.chatgpt.com/docs/agent-configuration/agents-md)
//   Cursor       .cursor/rules/*.mdc with description / globs / alwaysApply front matter;
//                globs is a comma-separated string; alwaysApply: true ignores the others
//                (cursor.com/docs/context/rules)
//   Copilot      .github/copilot-instructions.md, plain markdown, no front matter; Copilot
//                also reads AGENTS.md, CLAUDE.md and GEMINI.md
//                (docs.github.com/en/copilot/customizing-copilot/adding-repository-custom-instructions-for-github-copilot)
//   Gemini CLI   GEMINI.md in the project root and parents, @file.md imports, no front matter
//                (geminicli.com/docs/cli/gemini-md/)
//   llms.txt     H1, blockquote, free markdown without headings, then H2 link lists
//                (llmstxt.org)
import { rulesSource } from './source.js';
import type { RuleSection, RulesSource } from './source.js';

export type Format = 'claude' | 'agents' | 'cursor' | 'copilot' | 'gemini' | 'llms' | 'llms-full';

export const formats: readonly Format[] = ['claude', 'agents', 'cursor', 'copilot', 'gemini', 'llms', 'llms-full'];

/** Where each format lands, relative to the target directory. */
export const targetPath: Readonly<Record<Format, string>> = {
  claude: 'CLAUDE.md',
  agents: 'AGENTS.md',
  cursor: '.cursor/rules/redbelly.mdc',
  copilot: '.github/copilot-instructions.md',
  gemini: 'GEMINI.md',
  llms: 'llms.txt',
  'llms-full': 'llms-full.txt',
};

export const GENERATOR = '@gatedpath/agent-rules';
export const CLI = 'redbelly-agent-rules';
/**
 * How to run this package with npx. The PACKAGE name, never the bin name: `redbelly-agent-rules` is
 * not a package, nobody owns that name on npm, and an agent told to `npx` it would run whatever a
 * stranger later published there (audit of 2026-09-19).
 */
export const NPX = 'npx -y @gatedpath/agent-rules';

/** Site-relative link targets that don't exist yet. Rendered as a TODO(site) comment, not a dangling link. */
const SITE_TODO = [
  '/agents (rules files, MCP install, llms.txt)',
  '/start (golden path)',
  '/recipes (eligibility recipes)',
  '/tutorials (prompt cards)',
];

const generatedNotice = (fileName: string, howToEdit = `edit packages/agent-rules/src/source.ts and run \`${NPX} --out .\``): string =>
  `<!-- ${fileName} is generated by ${GENERATOR}. Don't edit it here: ${howToEdit}. -->`;

function renderSection(section: RuleSection, level: 2 | 3 = 2): string {
  const h = '#'.repeat(level);
  const out: string[] = [`${h} ${section.heading}`, ''];
  if (section.intro) out.push(section.intro, '');
  for (const rule of section.rules) out.push(`- ${rule}`);
  out.push('');
  if (section.links && section.links.length > 0) {
    out.push('Reference:', '');
    for (const l of section.links) out.push(`- [${l.label}](${l.url})${l.note ? `: ${l.note}` : ''}`);
    out.push('');
  }
  if (section.verified) out.push(`Verified ${section.verified}.`, '');
  return out.join('\n');
}

/** The shared markdown body. Identical in every rules-file format. */
export function renderBody(source: RulesSource = rulesSource): string {
  return source.sections.map((s) => renderSection(s)).join('\n').trimEnd() + '\n';
}

/** The chain-definitions notes, quoted verbatim as a fenced block. */
function renderAgentNotes(source: RulesSource): string {
  return ['## Facts in one block', '', `Quoted from \`agentNotes\` in @gatedpath/chains, which is canonical.`, '', '```', source.agentNotes, '```', ''].join('\n');
}

function renderRulesFile(source: RulesSource, opts: { fileName: string; title: string; audience: string; frontMatter?: string }): string {
  const parts: string[] = [];
  if (opts.frontMatter) parts.push(opts.frontMatter);
  parts.push(
    `# ${opts.title}`,
    '',
    generatedNotice(opts.fileName),
    '',
    `> ${source.summary}`,
    '',
    opts.audience,
    '',
    `Facts verified ${source.verified}. Vine and docs.redbelly.network are the reference; if this file and Vine disagree, Vine wins and this file needs regenerating.`,
    '',
    renderBody(source),
    renderAgentNotes(source),
  );
  return parts.join('\n').trimEnd() + '\n';
}

export function renderClaude(source: RulesSource = rulesSource): string {
  return renderRulesFile(source, {
    fileName: 'CLAUDE.md',
    title: source.title,
    audience: 'Claude Code reads this file at the start of every session. Keep it at the project root; a `.claude/rules/` file can add path-scoped rules on top. To share these rules with other tools, `AGENTS.md` carries the same content.',
  });
}

export function renderAgents(source: RulesSource = rulesSource): string {
  return renderRulesFile(source, {
    fileName: 'AGENTS.md',
    title: source.title,
    audience: 'Codex CLI, GitHub Copilot, Cursor and other agents that follow the AGENTS.md convention read this file from the repository root. Nested AGENTS.md files in subdirectories take precedence for their subtree, so keep this one at the root.',
  });
}

export function renderCursor(source: RulesSource = rulesSource): string {
  const frontMatter = [
    '---',
    'description: Redbelly Network (151 mainnet, 153 testnet) facts and rules for every file in this project. Chain IDs, gas model, identity gate, key handling, never-do list.',
    'globs:',
    'alwaysApply: true',
    '---',
  ].join('\n');
  return renderRulesFile(source, {
    fileName: '.cursor/rules/redbelly.mdc',
    title: source.title,
    audience: 'Cursor applies this rule to every conversation (`alwaysApply: true`). It is a Project Rule under `.cursor/rules/`, the location Cursor documents for version-controlled rules.',
    frontMatter,
  });
}

export function renderCopilot(source: RulesSource = rulesSource): string {
  return renderRulesFile(source, {
    fileName: '.github/copilot-instructions.md',
    title: source.title,
    audience: 'GitHub Copilot reads this file for every chat and agent request in the repository. Path-specific instructions can be added as `.github/instructions/NAME.instructions.md` with an `applyTo` front matter.',
  });
}

export function renderGemini(source: RulesSource = rulesSource): string {
  return renderRulesFile(source, {
    fileName: 'GEMINI.md',
    title: source.title,
    audience: 'Gemini CLI loads this file from the project root and from parent directories. It supports `@file.md` imports; none are used here so the file stands alone.',
  });
}

function compactFacts(source: RulesSource): string[] {
  // Free-markdown block for llms.txt: the facts and the never-do list as plain bullets,
  // no headings, so the file stays inside the llmstxt.org shape.
  const out: string[] = [];
  const pick = (id: string) => source.sections.find((s) => s.id === id);
  const chain = pick('chain-facts');
  const gas = pick('gas');
  const identity = pick('identity');
  const speeds = pick('two-speeds');
  const keys = pick('keys');
  const never = pick('never-do');
  for (const s of [chain, gas, identity, speeds, keys]) if (s) for (const r of s.rules) out.push(`- ${r}`);
  if (never) for (const r of never.rules) out.push(`- Never: ${r}`);
  return out;
}

function renderLinkSections(source: RulesSource): string[] {
  const out: string[] = [];
  for (const s of source.sections) {
    if (!s.links || s.links.length === 0) continue;
    out.push(`## ${s.heading}`, '');
    for (const l of s.links) out.push(`- [${l.label}](${l.url})${l.note ? `: ${l.note}` : ''}`);
    out.push('');
  }
  out.push('## Rules files', '');
  out.push(`- [Rendered samples](https://www.npmjs.com/package/@gatedpath/agent-rules?activeTab=code): CLAUDE.md, AGENTS.md, Cursor, Copilot, Gemini`);
  out.push(`- [Generator](https://www.npmjs.com/package/@gatedpath/agent-rules): ${GENERATOR}, run \`${NPX} --out .\``);
  out.push('');
  out.push(`<!-- TODO(site): the builder site does not exist yet. When it does, add these site-relative links here: ${SITE_TODO.join('; ')}. -->`, '');
  return out;
}

export function renderLlms(source: RulesSource = rulesSource): string {
  const out: string[] = [
    `# ${source.title}`,
    '',
    `> ${source.summary}`,
    '',
    `Facts verified ${source.verified}. This index links to Redbelly's own reference pages and lists the rules an agent must hold. The full text is in llms-full.txt.`,
    '',
    ...compactFacts(source),
    '',
    ...renderLinkSections(source),
  ];
  return out.join('\n').trimEnd() + '\n';
}

export function renderLlmsFull(source: RulesSource = rulesSource): string {
  const out: string[] = [
    `# ${source.title}`,
    '',
    `> ${source.summary}`,
    '',
    `Facts verified ${source.verified}. This is the full text of the rules; llms.txt is the short index. Draft: the builder site is not live, so links go to Vine, docs.redbelly.network, Routescan and GitHub.`,
    '',
    renderBody(source),
    renderAgentNotes(source),
    ...renderLinkSections(source),
  ];
  return out.join('\n').trimEnd() + '\n';
}

const renderers: Readonly<Record<Format, (s: RulesSource) => string>> = {
  claude: renderClaude,
  agents: renderAgents,
  cursor: renderCursor,
  copilot: renderCopilot,
  gemini: renderGemini,
  llms: renderLlms,
  'llms-full': renderLlmsFull,
};

export function render(format: Format, source: RulesSource = rulesSource): string {
  const fn = renderers[format];
  if (!fn) throw new Error(`unknown format ${format}; known: ${formats.join(', ')}`);
  return fn(source);
}

export function renderAll(source: RulesSource = rulesSource): Record<Format, string> {
  const out = {} as Record<Format, string>;
  for (const f of formats) out[f] = render(f, source);
  return out;
}

export function isFormat(value: string): value is Format {
  return (formats as readonly string[]).includes(value);
}
